Repository Atom-Learning/components, pull requests merged in 2022-09, with the labels that each got.

#391 Display px value in docs
  site/src/components/Scale.tsx
Labels: enhancement

#384 Feat/chip component refactor
  lib/package.json
  lib/scripts/add-component.mjs
  lib/src/components/chip-dismissible-group/ChipDismissibleGroup.mdx
  lib/src/components/chip-dismissible-group/ChipDismissibleGroup.test.tsx
  lib/src/components/chip-dismissible-group/ChipDismissibleGroupItem.tsx
  lib/src/components/chip-dismissible-group/ChipDismissibleGroupRoot.tsx
  lib/src/components/chip-dismissible-group/__snapshots__/ChipDismissibleGroup.test.tsx.snap
  lib/src/components/chip-dismissible-group/index.ts
  lib/src/components/chip-toggle-group/ChipToggleGroup.mdx
  lib/src/components/chip-toggle-group/ChipToggleGroup.test.tsx
  lib/src/components/chip-toggle-group/ChipToggleGroupItem.tsx
  lib/src/components/chip-toggle-group/ChipToggleGroupRoot.tsx
  lib/src/components/chip-toggle-group/__snapshots__/ChipToggleGroup.test.tsx.snap
  lib/src/components/chip-toggle-group/index.ts
  lib/src/components/chip/Chip.mdx
  lib/src/components/chip/Chip.test.tsx
  lib/src/components/chip/Chip.tsx
  lib/src/components/chip/ChipGroup.tsx
  lib/src/components/chip/__snapshots__/Chip.test.tsx.snap
  lib/src/components/chip/index.ts
  lib/src/components/dismissible-group/DismissibleGroup.mdx
  lib/src/components/dismissible-group/DismissibleGroup.test.tsx
  lib/src/components/dismissible-group/DismissibleGroupItem.tsx
  lib/src/components/dismissible-group/DismissibleGroupRoot.tsx
  lib/src/components/dismissible-group/__snapshots__/DismissibleGroup.test.tsx.snap
  lib/src/components/dismissible-group/index.ts
  lib/src/components/dismissible/Dismissible.mdx
  lib/src/components/dismissible/Dismissible.test.tsx
  lib/src/components/dismissible/DismissibleRoot.tsx
  lib/src/components/dismissible/DismissibleTrigger.tsx
  lib/src/components/dismissible/__snapshots__/Dismissible.test.tsx.snap
  lib/src/components/dismissible/index.ts
  lib/src/components/index.ts
  lib/src/components/stack/Stack.tsx
  lib/src/utilities/override-stitches-variant-value/overrideStitchesVariantValue.ts
  site/src/utilities/transform-navigation-structure.ts
Labels: enhancement, help wanted

#397 feat: search field
  lib/src/components/index.ts
  lib/src/components/search-field/SearchField.mdx
  lib/src/components/search-field/SearchField.test.tsx
  lib/src/components/search-field/SearchField.tsx
  lib/src/components/search-field/__snapshots__/SearchField.test.tsx.snap
  lib/src/components/search-field/index.ts
  lib/src/components/search-input/SearchInput.tsx
  lib/src/components/search-input/index.ts
  site/src/sandbox/components.tsx
Labels: enhancement

#395 fix/ds-75 adding image to empty state doc
  lib/src/components/empty-state/EmptyState.mdx
Labels: bug

#394 fix/ds-91 removing marging bottom from label wrapper when there is no label
  lib/src/components/field-wrapper/FieldWrapper.tsx
  lib/src/components/select-field/SelectField.tsx
Labels: bug
