Repository Atom-Learning/components, pull requests merged in 2022-11, with the labels that each got.

#423 feat: added noCapsize prop to Text based components, added fix for ov…
  lib/src/components/chip/Chip.tsx
  lib/src/components/heading/Heading.tsx
  lib/src/components/label/Label.tsx
  lib/src/components/link/Link.tsx
  lib/src/components/link/__snapshots__/Link.test.tsx.snap
  lib/src/components/list/List.tsx
  lib/src/components/list/__snapshots__/List.test.tsx.snap
  lib/src/components/markdown-content/__snapshots__/MarkdownContent.test.tsx.snap
  lib/src/components/stack-content/__snapshots__/StackContent.test.tsx.snap
  lib/src/components/text/Text.tsx
Labels: bug, enhancement

#427 feat: replace span element in link buttons with noCapsize
  lib/src/components/link/Link.tsx
  lib/src/components/link/__snapshots__/Link.test.tsx.snap
Labels: enhancement

#428 feat: pass onClick prop onto anchor links
  lib/src/components/link/Link.tsx
Labels: invalid

#415 feat: ColorScheme alpha version
  color-scheme/.eslintignore
  color-scheme/.eslintrc
  color-scheme/.lintstagedrc
  color-scheme/.prettierignore
  color-scheme/.prettierrc
  color-scheme/README.mdx
  color-scheme/package.json
  color-scheme/rollup.config.js
  color-scheme/src/ColorScheme.tsx
  color-scheme/src/blue.json
  color-scheme/src/generateAlphaColors.ts
  color-scheme/src/index.ts
  color-scheme/src/slate.json
  color-scheme/src/stitches.colorscheme.config.ts
  color-scheme/tsconfig.json
  color-scheme/yarn.lock
Labels: enhancement, help wanted

#434 feat: space out all children of StackContent
  lib/src/components/markdown-content/__snapshots__/MarkdownContent.test.tsx.snap
  lib/src/components/stack-content/StackContent.tsx
  lib/src/components/stack-content/__snapshots__/StackContent.test.tsx.snap
Labels: enhancement
