Repository Atom-Learning/components, pull requests merged in 2023-08, with the labels that each got.

#545 Badge: New emphasis, themes and overflow truncation features
  documentation/content/components.feedback.badge.md
  lib/src/components/action-icon/ActionIcon.tsx
  lib/src/components/badge/Badge.context.tsx
  lib/src/components/badge/Badge.tsx
  lib/src/components/badge/BadgeIcon.tsx
  lib/src/components/badge/BadgeText.tsx
  lib/src/components/badge/__snapshots__/Badge.test.tsx.snap
  lib/src/components/badge/stitches.badge.colorscheme.config.ts
  lib/src/components/data-table/DataTableGlobalFilter.tsx
  lib/src/utilities/optional-tooltip-wrapper/OptionalTooltipWrapper.test.tsx
  lib/src/utilities/optional-tooltip-wrapper/OptionalTooltipWrapper.tsx
  lib/src/utilities/optional-tooltip-wrapper/__snapshots__/OptionalTooltipWrapper.test.tsx.snap
  lib/src/utilities/optional-tooltip-wrapper/index.ts
  lib/src/utilities/optional-visually-hidden-wrapper/OptionalVisuallyHiddenWrapper.test.tsx
  lib/src/utilities/optional-visually-hidden-wrapper/OptionalVisuallyHiddenWrapper.tsx
  lib/src/utilities/optional-visually-hidden-wrapper/__snapshots__/OptionalVisuallyHiddenWrapper.test.tsx.snap
  lib/src/utilities/optional-visually-hidden-wrapper/index.ts
  lib/src/utilities/optionally-visually-hidden-container/OptionallyVisuallyHiddenContainer.test.tsx
  lib/src/utilities/optionally-visually-hidden-container/index.ts
Labels: enhancement

#555 fix: theme type of Badge not correct
  lib/src/components/badge/stitches.badge.colorscheme.config.ts
Labels: bug

#556 fix: wrong badge typescript output, simplify, mod colours to design a…
  documentation/content/components.feedback.badge.md
  lib/src/components/badge/Badge.tsx
  lib/src/components/badge/__snapshots__/Badge.test.tsx.snap
  lib/src/components/badge/stitches.badge.colorscheme.config.ts
Labels: bug, documentation

#557 fix: use hashes for classes created via createTheme
  lib/src/components/accordion/__snapshots__/Accordion.test.tsx.snap
  lib/src/components/badge/__snapshots__/Badge.test.tsx.snap
  lib/src/components/badge/stitches.badge.colorscheme.config.ts
  lib/src/components/banner/banner-regular/__snapshots__/BannerRegular.test.tsx.snap
  lib/src/components/pagination/__snapshots__/Pagination.test.tsx.snap
  lib/src/components/tabs/__snapshots__/Tabs.test.tsx.snap
  lib/src/components/tile-interactive/__snapshots__/TileInteractive.test.tsx.snap
  lib/src/components/tile-toggle-group/__snapshots__/TileToggleGroup.test.tsx.snap
  lib/src/components/tile/__snapshots__/Tile.test.tsx.snap
  lib/src/experiments/color-scheme/stitches.colorscheme.config.ts
Labels: bug

#558 fix: add correct polymorphic types for Button component
  lib/src/components/button/Button.tsx
  lib/src/components/link/Link.tsx
  lib/src/components/stepper/StepperStepForward.tsx
  lib/src/types/index.ts
  lib/src/types/polymorphicComponentProp.types.ts
Labels: bug
