Repository Atom-Learning/components, pull requests merged in 2024-09, with the labels that each got.

#701 feat: focusVisibleStyleBlock allow boxShadow to be passed in
  lib/src/utilities/style/focus-visible-style-block.ts
Labels: enhancement

#702 fix: classname placement on Input
  lib/src/components/data-table/__snapshots__/DataTable.test.tsx.snap
  lib/src/components/input/Input.tsx
  lib/src/components/search-field/__snapshots__/SearchField.test.tsx.snap
  lib/src/components/search-input/SearchInput.tsx
  lib/src/components/search-input/__snapshots__/SearchInput.test.tsx.snap
Labels: bug

#621 refactor: prefer native [disabled] over [data-disabled] for styles ta…
  lib/src/components/accordion/AccordionTrigger.tsx
  lib/src/components/accordion/__snapshots__/Accordion.test.tsx.snap
  lib/src/components/chip-dismissible-group/__snapshots__/ChipDismissibleGroup.test.tsx.snap
  lib/src/components/chip-toggle-group/__snapshots__/ChipToggleGroup.test.tsx.snap
  lib/src/components/chip/Chip.tsx
  lib/src/components/chip/__snapshots__/Chip.test.tsx.snap
  lib/src/components/navigation-menu-vertical/NavigationMenuVertical.styles.ts
  lib/src/components/navigation-menu-vertical/__snapshots__/NavigationMenuVertical.test.tsx.snap
  lib/src/components/slider-field/__snapshots__/SliderField.test.tsx.snap
  lib/src/components/slider/Slider.tsx
  lib/src/components/slider/__snapshots__/Slider.test.tsx.snap
  lib/src/components/tabs/TabsTrigger.tsx
  lib/src/components/tabs/__snapshots__/Tabs.test.tsx.snap
Labels: Stale

#704 Feat/keyboard shortcut
  documentation/content/components.keyboard-shortcut.md
  lib/src/components/index.ts
  lib/src/components/keyboard-shortcut/KeyboardShortcut.test.tsx
  lib/src/components/keyboard-shortcut/KeyboardShortcut.tsx
  lib/src/components/keyboard-shortcut/__snapshots__/KeyboardShortcut.test.tsx.snap
  lib/src/components/keyboard-shortcut/index.ts
Labels: enhancement

#707 fix: readd auto width to search input
  lib/src/components/data-table/__snapshots__/DataTable.test.tsx.snap
  lib/src/components/search-field/__snapshots__/SearchField.test.tsx.snap
  lib/src/components/search-input/SearchInput.tsx
  lib/src/components/search-input/__snapshots__/SearchInput.test.tsx.snap
Labels: bug

#708 fix(navigation-menu-vertical): changing text opacity even if motion is reduced
  lib/src/components/navigation-menu-vertical/NavigationMenuVerticalText.tsx
  lib/src/components/navigation-menu-vertical/__snapshots__/NavigationMenuVertical.test.tsx.snap
Labels: bug
